dist: trusty
sudo: false
language: php
php:
- '7.2'
cache:
  directories:
  - "$HOME/.composer/cache"
  
before_script:
    - cp .env.travis .env
    - phpenv config-rm xdebug.ini
    - composer install --prefer-dist --no-interaction
    - touch database/database.sqlite
    - php artisan clear-compiled -n
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate

after_failure:
    - cat storage/logs/laravel.log

script:
    - vendor/bin/phpunit