version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
      - image: redis

    working_directory: ~/laravel

    steps:
      - checkout

      - run:
         name: Download NodeJS v8
         command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

      - run:
          name: Install PHP sqlite and nodejs 8
          command: sudo apt-get install -y libsqlite3-dev nodejs
      
      - run:
          name: Install GD library 
          command: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.circle .env

      - run:
         name: Update composer to latest version
         command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NodeJS Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
        
      # run tests!
      - run: touch database/database.sqlite
      - run: php artisan key:generate
      - run: npm run dev

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      - run: vendor/bin/phpunit